name: Publish Docker Image on Change

on:
  pull_request:
    paths:
      - 'templated_tests/**/Dockerfile'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Extract short sha
        id: short_sha
        run: |
          echo "{sha}={$(echo $GITHUB_SHA | cut -c1-7)}" >> $GITHUB_OUTPUT
          echo $(echo $GITHUB_SHA | cut -c1-7)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract image name
        id: image-name
        run: |
          echo '${{ github.event.pull_request.head.ref }}' | grep -oE 'test_integration/[^/]+/' | head -1 | cut -d'/' -f2
          echo '${{ github.event.pull_request.head.ref }}' | grep -oE 'test_integration/[^/]+/' | head -1 | cut -d'/' -f2 >> $GITHUB_OUTPUT

      - name: Build and push with commit tag
        uses: docker/build-push-action@v2
        with:
          context: ./test_integration/${{ steps.image-name.outputs.image }}
          file: ./test_integration/${{ steps.image-name.outputs.image }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.image-name.outputs.image }}:${{ steps.short-sha.outputs.sha }}

      # - name: Build and push with latest tag
      #   if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./test_integration/${{ steps.image-name.outputs.image }}
      #     file: ./test_integration/${{ steps.image-name.outputs.image }}/Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.image-name.outputs.image }}:latest