name: Update Docker Image Reference on PR

on:
  pull_request:
    paths:
      - 'templated_tests/**'

jobs:
  update-docker-reference:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get short SHA
        id: sha
        run: echo "::set-output name=short_sha::$(git rev-parse --short ${{ github.event.pull_request.head.sha }})"

      - name: Get parent directory names of changed files
        id: dirname
        run: |
          git diff --name-only origin/${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.head.ref }}
          changes_dirs=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.head.ref }} | grep 'templated_tests/' | xargs -I {} dirname {} | sort -u)
          echo ${changes_dirs}
          echo "::set-output name=changes_dirs::${changes_dirs}"

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: blazar00
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          # Assuming you have logged in to DockerHub in a previous step
          # Use the root directory name as the Docker image name and tag it with the commit SHA
          echo "Building and pushing Docker images for the following directories: ${{ steps.dirname.outputs.changes_dirs }}"
          for dir in ${{ steps.dirname.outputs.changes_dirs }}; do
            image=${dir//\//_}
            docker build -t blazar00/$image:${{ steps.sha.outputs.short_sha }} $dir
            docker push blazar00/$image:${{ steps.sha.outputs.short_sha }}
          done
